# Generated by Django 3.2 on 2023-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.SlugField(max_length=254, unique=True, verbose_name='Email пользователя'),
        ),
    ]
