# Generated by Django 3.2 on 2023-07-05 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\z', 'Поддерживаются тольо буквы, цифры и знаки @.+-_')], verbose_name='Юзернейм пользователя'),
        ),
    ]
