# Generated by Django 3.2 on 2023-07-05 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z', 'Поддерживаются тольо буквы, цифры и знаки @.+-_')], verbose_name='Юзернейм пользователя'),
        ),
    ]
