# Generated by Django 3.2 on 2023-07-05 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^(?!me)([\\w.@+-]+\\Z)$', 'Поддерживаются только буквы, цифры и знаки @.+-_\nЗначение "me" запрещено')], verbose_name='Юзернейм пользователя'),
        ),
    ]
