# Generated by Django 3.2 on 2023-07-05 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20230705_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Поддерживаются только латинские буквы, - и _', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Идентификатор категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Поддерживаются только латинские буквы, - и _', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Идентификатор жанра'),
        ),
    ]
