# Generated by Django 3.2 on 2023-07-06 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20230705_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Поддерживаются только латинские буквы, - и _', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Идентификатор категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Поддерживаются только латинские буквы, - и _', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Идентификатор жанра'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Поддерживаются только буквы, цифры и знаки @.+-_', regex='^[\\w.@+-]+$')], verbose_name='Юзернейм пользователя'),
        ),
    ]
