# Generated by Django 3.2 on 2023-07-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_rename_review_id_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='review_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='title_id',
        ),
    ]
