# Generated by Django 3.2 on 2023-07-10 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20230710_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Поддерживаются только буквы, цифры и знаки @.+-_')], verbose_name='Юзернейм пользователя'),
        ),
    ]
